name: .NET Core

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - dev

env:
  TargetNet8: True

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: true
    name: Wilson GitHub Action Test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Setup .NET 8.0.x
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x

    # Build and test
    - name: Restore packages
      run: dotnet restore Wilson.sln

    - name: Run the tests
      run: dotnet test Wilson.sln

    # Run baseline package validation
    - name: Pack
      run: .\pack.ps1
