name: .NET Core

on:
  push:
    branches:
      - dev7x
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - dev7x

env:
  TargetNet8: True

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: true
    name: Wilson GitHub Action Test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    - name: Setup .NET 6.0.301
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 6.0.301
    - name: Setup .NET 8.0.x
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 8.0.100-preview.6.23330.14
  
    # Build and test
    - name: Restore packages
      run: dotnet restore Wilson.sln
    - name: Run the tests
      run: dotnet test Wilson.sln
