name: .NET Core

on:
  push:
    branches:
      - dev7x
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - dev7x

env:
  TargetNet9: True
  TargetNet8: True

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: true
    name: Wilson GitHub Action Test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 6.0.x

    - name: Setup .NET 8.0.x
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET 9.0.x
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 9.0.100-preview.4.24267.66

    - name: Run the tests
      run: dotnet test Wilson.sln

    # Run baseline package validation
    - name: Pack
      run: dotnet pack Product.proj --no-restore --no-build
